GameOverScreen
heatlight/hour pull request #13
Opened 2023-01-04 10:11 UTC by heatlight

2023-01-04 21:08 UTC, lojbrooks requested changes
Looks good! Left a few comments, all just related to coding best practices, nothing that will change the behaviour. 👍

2023-01-04 21:08 UTC, lojbrooks commented on Assets/Scripts/GameBoard.cs
> +    public bool isChaining = false;
Can we keep this field as private and add a function to get the value.  Something like

`public bool IsChaining() {
   return isChaining;
}
`

This would make the field `isChaining` read only to other classes, and would adhere to the programming concept of encapsulation.

2023-01-04 21:08 UTC, lojbrooks commented on Assets/Scripts/GameManager.cs
> +    public bool gameOver = false;
Same for this bool as well, can we make it private and add a `public bool IsGameOver()` function? Seems insignificant but it's good to limit the visibility of fields if possible.

2023-01-06 16:26 UTC, heatlight commented on Assets/Scripts/GameBoard.cs
> +    public bool isChaining = false;
I'm having some issues getting this to work, it's returning a CS20023 error, doesn't like the ! on the new bool for some reason. I'm sure it's a really obvious fix.

2023-01-06 16:34 UTC, heatlight commented on Assets/Scripts/GameBoard.cs
> +    public bool isChaining = false;
Forget that, sorted it. :)

2023-01-06 16:41 UTC, lojbrooks approved these changes

2023-01-06 16:56 UTC, merged