UpdatedScoreAndBlocks
heatlight/hour pull request #20
Opened 2023-01-24 10:12 UTC by heatlight

Would appreciate your thoughts on all of this, there's a lot of changes to the game here. Also I'm sure there's a more elegant solution to the 'scalable score' method than lots of else if statements. Let me know what you think works and what doesn't, I won't take offence haha x

2023-01-24 17:00 UTC, lojbrooks requested changes
Haven't play tested this yet but added a few comments for now. Looks like some good improvements though! 👍

2023-01-25 08:59 UTC, heatlight commented on Assets/Scripts/GameManager.cs
> +            score += scalableScore;
So I did send a follow up email basically saying 'forget about all the combo changes', maybe you didn't get that. Been having some weird email issues lately. But yeah, I went back to the old system, didn't like the new one as it just got a bit confusing. My problem was that I wanted to have power ups later on increasing the multiplier but couldn't with the cap in place. I solved this by adding a separate 'bonus multiplier' that we can increase at will.

It now adds a bit of extra score every time you get a combo on top of the cap, which I thought was an appropriate bonus.

2023-01-25 09:00 UTC, heatlight commented on Assets/Scripts/GameManager.cs
> +                comboMultiplier = 1;
This is a carry over from that different combo mechanic, I was finding you could keep the multiplier at ridiculous heights and you would skip through levels too quickly. I'll change it back.

2023-01-25 09:02 UTC, heatlight commented on Assets/Scripts/GameManager.cs
> +        if (level == 2)
I actually tried to use the levelScores as the base for my scalableScore orginially, but I couldn't make it work. That unfortunately is my inexperience showing haha. We can always tidy it up later, at least it works.

2023-01-25 09:03 UTC, heatlight commented on Assets/Scripts/GameManager.cs
> +                    Debug.Log("Shield Active");
Yup, agreed. I thought when we've got all the visuals in place that tinting the hourglass green would be a cool visual trick, but in the meantime I'll just display some text.

2023-01-25 09:05 UTC, heatlight commented on Assets/Scripts/GameManager.cs
> +                /*case BlockType.Yellow:
Yeah I just left it there for now in case we decided we wanted to use it in future. I just didn't want to delete code you'd written really :)

2023-02-06 16:01 UTC, lojbrooks requested changes
Just a couple of minor things left. 👍

2023-02-06 16:17 UTC, heatlight commented on Assets/Scripts/GameManager.cs
> +    private int MAX_COMBO = 4;
Ah, I was wondering why that was like that. That explains it. :)

2023-02-06 16:19 UTC, heatlight commented on Assets/Scripts/GameManager.cs
>          gameBoard = FindObjectOfType<GameBoard>();
You have no idea how long I spent trying to get that Math.Pow thing to work for squaring values haha. Easy as that huh? :)

2023-02-06 17:43 UTC, lojbrooks approved these changes

2023-02-08 15:51 UTC, merged