Further rebalancing
heatlight/hour pull request #32
Opened 2023-03-27 13:53 UTC by heatlight

Few new things on here so I'll just go over them quickly...

Implemented new Level Block Spawner code with new power block percentages up to level 10.
Simplified some of the passive abilities. No need for them to get harsher at higher levels, time penalties are bad at any point in the game.
Increased Violet multiplier increase, as by the time you get round to this stage you already have a max cap of like 512. So 30 more isn't that much of an increase.
Violet now has both a positive and negative passive ability, as well as a positive and negative destroyed ability. Makes sense for continuity.
I have increased the base rate of score for matching combos. This makes the earlier levels a bit shorter, and means that making matches still helps at higher levels, whereas it was becoming a bit of an irrelevence before.
Changed the if/elses for the scalable score to work via a formula instead (this took me ages to work out, maths clearly no longer a strong point!)

Any thoughts on stuff you don't like or what you think needs changing, please shout up. :)

2023-03-28 15:20 UTC, lojbrooks requested changes

2023-03-28 15:20 UTC, lojbrooks commented on Assets/Scripts/BlockSpawner.cs
> +            case 10:
Bit of a nitpick but we could remove case 10.

2023-03-28 15:20 UTC, lojbrooks commented on Assets/Scripts/LevelBlockSpawner.cs
Can you just do an Edit -> Format -> Format Document on this file? The indentation is a bit messed up I think.

2023-03-29 10:20 UTC, heatlight commented on Assets/Scripts/BlockSpawner.cs
> +            case 10:
Is this because it will default to level 10 if none of the other cases are true?

2023-03-29 10:23 UTC, heatlight commented on Assets/Scripts/LevelBlockSpawner.cs
Wow, I didn't realise that was a thing haha. Sorted.

2023-03-29 15:17 UTC, lojbrooks commented on Assets/Scripts/BlockSpawner.cs
> +            case 10:
Yep, exactly that. 👍

2023-03-29 15:18 UTC, lojbrooks approved these changes

2023-03-29 15:28 UTC, lojbrooks commented on Assets/Scripts/GameManager.cs
> +        scalableScore = (int)(Math.Pow(5, level - 1) * 2);
Only place it would be relevant on level 1 is if you get a match but are already at the max combo, then it adds scalable score to score. Think the change is fine though tbh.

2023-04-04 18:11 UTC, merged